### ISSUE TITLE
Name of user is outrageous.

### ISSUE THREAD

**Issue by lhugens** [cesarium/da-bayesian-star#1]
I'm sorry, I'm not sure who you think you are, but are you so full of yourself that you think you are a new chemical element or something? 

Get a grip.

With love, 
huggabalanga

**Comment by cesarium** [comment]
Dear huggabalanga,

Well yes, I'm a talking element. God made me with a lot of charm (quarks) lmao

Thank you for your question.

Have an A1 day,
cesarium , Z = 300 A = 301
